public enum STOReputationOrganization: String, CaseIterable, Codable, CodingKey {
    case Omega = "Task Force Omega"
    case Nukara = "Nukara Strikeforce"
    case NewRomulus = "New Romulus"
    case Dyson = "Dyson Joint Command"
    case Undine = "8472 Counter Command"
    case Delta = "Delta Alliance"
    case Iconian = "Iconian Resistance"
    case Terran = "Terran Task Force"
    case Temporal = "Temporal Defense Initiative"
    case Lukari = "Lukari Restoration Initiative"
    case Competitive = "Competitive Wargames"
    case Gamma = "Gamma Task Force"
    case Discovery = "Discovery Legends"
}
